### ISSUE TITLE
[Suggestion] Brightness Option for the Text?

### ISSUE THREAD

**Issue by SonicX8000** [kevin68/The-Spotlight-Mod#10]
This would be for 1.12.2 & up.

![](https://cdn.discordapp.com/attachments/377171551155650560/676225534174429254/spotlightbrightness.PNG)

I was wonder if there could be an option to adjust the brightness for the Text or a Full Bright option, whether it be 2D or 3D... as currently the default brightness for the 2D Text seems a bit... dark even though it's set a R:255, G:255, B:000... however the 3D Text looks fine in terms of brightness.

I also tossed in a Yellow Antiblock from the Chisel Mod just to compare the brightness for the text. That block appears full bright no matter the light level.

P.S.
I wonder if there could be a rainbow color cycle config option for the beacon beam & text, if possible.

**Comment by robin4002** [comment]
Hi,
Thank for the report.
I confirm that there is a problem with the color of 2D text, I will try to fix that this week.

 To make a rainbow cycle, you can use the timeline feature to change colors over time.

**Comment by SonicX8000** [comment]
Oh? Didn't know it was actually a bug with the 2D Text.

Timeline feature... I gotta try to experiment with that.
