### ISSUE TITLE
Pressing "E" On Text option closes the menu

### ISSUE THREAD

**Issue by RyanCR03** [kevin68/The-Spotlight-Mod#11]
Using The Text option when i try to type "Minecraft" It closes in the middle of writing it, then it just says "min". i found out that even if you are selecting the text box pressing "E" will close the menu.

**Comment by robin4002** [comment]
Hi,
Thank for the bug reporting.
This was a really stupid bug (I do not understand how I did not to notice it rather, E is the most used character in my native language x)). It will be fixed in the next release.
