### ISSUE TITLE
Center Texts

### ISSUE THREAD

**Issue by D3nnis3n** [kevin68/The-Spotlight-Mod#5]
Hey, i wanted to make a Suggestion:
At the Moment when in text mode, Texts you write are not centered above your Spotlight, but seem to be much more left than reight of the Block. It would be great if you could make it so it's centered as much as possible, or make an Option for this in the Spotlight.

**Comment by robin4002** [comment]
Hi,
We already use center function to draw the text.
And it's works perfectly : 
![2017-10-21_11 55 41](https://user-images.githubusercontent.com/1993583/31850690-eef51092-b656-11e7-8453-ca46ae4b9bc9.png)

With what text and parameter do you have a problem ?

**Comment by D3nnis3n** [comment]
3D Text, primarily:
https://ibb.co/b155wR

This is one of the better examples. There are worse. I just Need to remember which Texts, as we did not use them, then. It already Looks bad on this Building because you notice it so much cause of the form of the Buildings upper part.

**Comment by robin4002** [comment]
I reproduced the bug, it should be fixed in the next update.
