### ISSUE TITLE
Colour Crash

### ISSUE THREAD

**Issue by SanderCN** [kevin68/The-Spotlight-Mod#8]
When placing a spotlight down and trying to change the colours you get disconnected.
Tested with the same mods and everything else in Singleplayer and no problems

**Comment by robin4002** [comment]
Hi,
Can you send the client's logs and the server's logs after the disconnection ?

**Comment by SanderCN** [comment]
Server log: https://pastebin.com/GD9nvUUn
Client log: https://pastebin.com/AkdkDhik

**Comment by robin4002** [comment]
Look like you are using a modified forge server that include the bukkit api, but the implementation is broken.
```
java.lang.NoSuchMethodError: net.minecraft.network.play.client.CPacketCloseWindow.<init>(I)V
    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:790) ~[CraftEventFactory.class:git-HEAD-b7c2f7d]
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:107
```` 
The method callInventoryOpenEvent from the bukkit implementation try to use a constructor that doesn't exist.
This bug isn't caused by The SpotLight Mod but by your type of server.
